---
abstract: 'Glue to power HTML::Zoom with HTML::Parser'
author:
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTML::Zoom: 0
  HTML::Zoom::CodeStream: 0
  HTML::Zoom::FilterBuilder: 0
  HTML::Zoom::FilterStream: 0
  HTML::Zoom::Producer::BuiltIn: 0
  HTML::Zoom::SelectorParser: 0
  Module::Build: 0.3601
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Zoom-Parser-HTML-Parser
provides:
  HTML::Zoom::Parser::HTML::Parser:
    file: lib/HTML/Zoom/Parser/HTML/Parser.pm
    version: 1.130810
requires:
  HTML::Entities: 0
  HTML::TokeParser: 0
  HTML::Zoom::SubObject: 0
  base: 0
  strictures: 1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=HTML-Zoom-Parser-HTML-Parser
  homepage: http://search.cpan.org/dist/HTML-Zoom-Parser-HTML-Parser/
  repository: https://github.com/mattp-/HTML-Zoom-Parser-HTML-Parser.git
version: 1.130810
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: ReadmeMarkdownFromPod
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@Filter/AutoVersion'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.04
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Filter/PruneFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git::Check'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git::Commit'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Filter/Git::CommitBuild'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/TagMaster'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/TagRelease'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git::Push'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300030
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300030
